### ISSUE TITLE
Add --check-only option (PACMAN-605)

### ISSUE THREAD

**Issue by tore-espressif** [espressif/upload-components-ci-action#10]
In many repositories, we run this GH action after a PR was merged to `master` branch. But then, we sometimes fail on invalid manifest format. I would like to run this action with `compote --check-only` argument in the PR pipeline, so we can check correct format of the manifest before merging it.

There are other ways of implementing the same:
* dedicated GH action that would call `compote --check-only`
* Implementing pre-commit check with the same functionality

Let me know, if you have any preferences/ideas. Thanks!

@kumekay @igrr 
Related: https://github.com/espressif/idf-extra-components/pull/147

**Comment by kumekay** [comment]
@tore-espressif Thank you for opening the issue, 

`compote component upload --check-only` only checks if the given version was already uploaded. While it checks the correctness of the manifest format, it doesn't perform numerous checks that only happen in the registry. This check, however, is quick enough and can happen in the pre-commit hook. 

An API endpoint for the full set of checks is already implemented but not exposed as a CLI command. We will implement it in the coming release. Then we will add an option to perform this check in this action. However, this server-side check is too slow for a pre-commit hook.

**Comment by tore-espressif** [comment]
@kumekay thanks for the ideas. 

As of now, should I just call `compote component upload --check-only` in a custom GH workflow? That is, without this `upload-component-ci-action`?

**Comment by kumekay** [comment]
@tore-espressif You can call "compote component upload --check-only" in a custom workflow. As I mentioned above, it will check the manifest format, but the component upload may fail for other reasons.

I want to keep this issue open, and we will add a parameter to this action once a CLI is released.

**Comment by kumekay** [comment]
Fixed by https://github.com/espressif/upload-components-ci-action/pull/12
