### ISSUE TITLE
Don't fail on first error when uploading multiple components (PACMAN-732)

### ISSUE THREAD

**Issue by kumekay** [espressif/upload-components-ci-action#13]
Currently, the action fails as soon as the first component upload fails. For example: https://github.com/espressif/idf-extra-components/actions/runs/6299066084/job/17099112378

It should try to upload every component first, and then print the list of failed uploads

**Comment by igrr** [comment]
Another related case is when uploading two new components, one of which depends on the other. Currently we have to specify them in the correct order (dependee first, dependent later.) If this feature is implemented, we can at least retry the action and both components will get uploaded.
