### ISSUE TITLE
How to get a GitHub badge that shows the status of the latest push?  (PACMAN-460)

### ISSUE THREAD

**Issue by chmorgan** [espressif/upload-components-ci-action#5]
I'd like to add a badge to the main branch README.md to show the status of the latest push but the preview for it is showing failure, thoughts?

https://github.com/chmorgan/esp-audio-player/actions/workflows/esp_upload_component.yml

**Comment by kumekay** [comment]
Hi @chmorgan
What code are you using? If you just put it like: 

`![Component upload](https://github.com/chmorgan/esp-audio-player//actions/workflows/esp_upload_component.yml/badge.svg)`

![Component upload](https://github.com/chmorgan/esp-audio-player//actions/workflows/esp_upload_component.yml/badge.svg)

It shows the most recent status for the `main` branch, this [run](https://github.com/chmorgan/esp-audio-player/actions/runs/2963995898)

However, the job now runs only for tags, and if you specify one it will work:

`![Component upload](https://github.com/chmorgan/esp-audio-player//actions/workflows/esp_upload_component.yml/badge.svg?branch=v1.0.3)`

![Component upload](https://github.com/chmorgan/esp-audio-player//actions/workflows/esp_upload_component.yml/badge.svg?branch=v1.0.3)

Unfortunately, don't know a way to generate the badge for the most recent tag, to include it to the Readme

**Comment by chmorgan** [comment]
@kumekay hmm.... yeah I'd have to update the badge each time a new rev was pushed up, which *could* work but feels clunky. There must be some way to get the status of the latest push?  Oh well.

**Comment by kumekay** [comment]
@chmorgan Unfortunately Github Action badges are somewhat limited. 

A way to solve your problem is to use more GitHub actions! With  https://github.com/marketplace/actions/badge-action you generate the right action image and then upload it to GitHub pages with https://github.com/peaceiris/actions-gh-pages

Also, we are going to add an endpoint to the component registry to generate badges for components with the latest version. It's not the same thing, but may be useful too.

**Comment by chmorgan** [comment]
@kumekay problems with actions? Use more actions!!!   I might take a look at that in the future but likely going to drop it for now.

A badge for latest version would be helpful though. I'd put that in the README.md files.

**Comment by kumekay** [comment]
@chmorgan You can now generate badges with the latest version:

[![Component Registry](https://components.espressif.com/components/chmorgan/esp-audio-player/badge.svg)](https://components.espressif.com/components/chmorgan/esp-audio-player)

You can find the code in right hand menu:
https://components.espressif.com/components/chmorgan/esp-audio-player

**Comment by chmorgan** [comment]
Cool! How was this fixed?

**Comment by kumekay** [comment]
@chmorgan These are not Github badges, these are generated by the components registry.

**Comment by kumekay** [comment]
@chmorgan I would like to close this issue. 

Even though we cannot solve the original problem with CI action badges,
I hope the badge with the latest version is a good enough alternative. 

If there is anything else we can help you with, feel free to reopen this issue.

**Comment by chmorgan** [comment]
@kumekay oh that works ok even though its not part of the CI system it looks helpful since it will give users a quick link and quick info about the latest published version. Thank you for implementing this.
